---
deployment:
 tasks:
 - export DEPLOYPATH=/home/chialinkhern/public_html/repositories/test_deploy/
 - /bin/cp -R superprime $DEPLOYPATH
 - /bin/cp -R jsPsych-6.3.0 $DEPLOYPATH
 - /bin/cp -R Stimuli $DEPLOYPATH
 - /bin/cp -R index.html $DEPLOYPATH
 - /bin/cp -R KaraConsentForm.html $DEPLOYPATH
 - /bin/cp -R test $DEPLOYPATH
 - /bin/cp -R README.md $DEPLOYPATH